channels = ["rapidsai", "nvidia", "conda-forge"]

[deps]
cudf = "=23.10"
cuxfilter = "=23.10"
cucim = "=23.10"
cuspatial = "=23.10"
cugraph = "=23.10"
cuml = "=23.10"
python = ">=3.9,<3.11"

    [deps.cuda-version]
    channel = "conda-forge"
    version = "=12.0"
