channels = ["rapidsai", "nvidia", "conda-forge"]

[deps]
cudf = "=23.08"
cuda-version = "=12.0.0"
cuxfilter = "=23.08"
cucim = "=23.08"
cuspatial = "=23.08"
cugraph = "=23.08"
cusignal = "=23.08"
cuml = "=23.08"
python = ">=3.9,<=3.10"
